---
settings:
  analysis:
    analyzer:
      # Don't use ngram for search otherwise 'horribleexample' would match
      # 'horriblesubs'
      nyaapantsu_search_analyzer:
        tokenizer: standard
        filter:
          - standard
          - lowercase
        char_filter:
          - crc32_fix # This should be run first
          - underscore_to_space
          - trim_zeros
          - resolution
          - dash_to_underscore
          - remove_quotes
          - resolution_fix

      nyaapantsu_index_analyzer:
        tokenizer: standard
        filter:
          - standard
          - lowercase
          - e_ngram_filter
        char_filter:
          - crc32_fix # This should be run first
          - underscore_to_space
          - trim_zeros
          - resolution
          - dash_to_underscore
          - remove_quotes
          - resolution_fix

      nyaapantsu_language_analyzer:
        tokenizer: comma_separator_tokenizer

    tokenizer:
      comma_separator_tokenizer:
        type: pattern
        pattern: ","

    filter:
      e_ngram_filter:
        type: edge_ngram
        min_gram: 1
        max_gram: 16

    char_filter:
      dash_to_underscore:
        type: pattern_replace
        pattern: "\\b([^\\s]{1,3})-(?=[^\\s]{1,3})"
        replacement: "$1_"

      trim_zeros:
        type: pattern_replace
        pattern: "\\b0+([123456789])"
        replacement: "$1"

      resolution:
        type: pattern_replace
        pattern: "(\\d+)[xX](\\d+)"
        replacement: "$1 $2"

      remove_quotes:
        type: pattern_replace
        pattern: "['`]"
        replacement: ""

      underscore_to_space:
        type: mapping
        mappings:
          - "_ => \\u0020"

      # This fixes the following (and similar) scenario:
      # Searching for episode 19 for a series gives all episode of that series
      # because it had 1920 x 1080 resolution
      # The random string below must not be too long for now because the n-gram
      # accepts only 16 characters
      # Prepending arabic symbol to avoid conflicts
      resolution_fix:
        type: pattern_replace
        pattern: "\\b(1920|1280|1024|1080p?|900p?|720p?|576p?|480p?)\\b"
        replacement: "تresoluti$1"

      # The random string below must not be too long for now because the n-gram
      # accepts only 16 characters
      # Prepending arabic symbol to avoid conflicts
      crc32_fix:
        type: pattern_replace
        pattern: "\\b(\\p{XDigit}{8})\\b"
        replacement: "بcrc32$1"

  index:
    number_of_shards: 1
    number_of_replicas: 0
    max_result_window: 5000000

mappings:
  torrents:
    properties:
      # TODO Consistent ID's type in TorrentJSON
      id:
        type: long
      name:
        type: text
        analyzer: nyaapantsu_index_analyzer
        fields:
          raw:
            type: keyword
      category:
        type: text
      description:
        type: text
      sub_category:
        type: text
      status:
        type: long
      hash:
        type: text
      date:
        type: date
      uploader_id:
        type: long
      downloads:
        type: long
      hidden:
        type: boolean
      filesize:
        type: long
      language:
        type: text
        analyzer: nyaapantsu_language_analyzer
      seeders:
        type: long
      leechers:
        type: long
      completed:
        type: long
      last_scrape:
        type: date
