- name: Download postgresql rpm
  get_url:
    url: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    dest: /tmp/postgresql.rpm

- name: Install postgresql.rpm
  yum:
    name: /tmp/postgresql.rpm
    state: present
  become: true

- name: Install postgresql
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - postgresql96-server
    - postgresql96-contrib # Needed for extensions (ie: btree_gin)

- name: Add go to PATH
  lineinfile:
    path: ~/.bashrc
    regexp: 'export PATH=.*pgsql.*'
    line:   'export PATH=$PATH:/usr/pgsql-9.6/bin'

- name: Initialize postgresql
  command: /usr/pgsql-9.6/bin/initdb -D /var/lib/pgsql/9.6/data
  # Will error when database has already been initialized so just ignore it
  ignore_errors: yes
  become: true
  become_user: postgres

- name: Copy configuration file for postgresql
  template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/9.6/data/postgresql.conf
  become: true
  become_user: postgres


- name: Install adapter for python
  yum:
    name: python-psycopg2
    state: present
  become: true

- name: Start postgresql and enable at boot
  systemd:
    enabled: yes
    name: postgresql-9.6
    state: started
  become: true

- name: Create nyaapantsu database
  postgresql_db:
    name: "{{ nyaapantsu_dbname }}"
  become: true
  become_user: postgres

# TODO Probably better idea to not set SUPERUSER
- name: Create nyaapantsu user
  postgresql_user:
    db: "{{ nyaapantsu_dbname }}"
    name: "{{ nyaapantsu_user }}"
    password: "{{ nyaapantsu_password }}"
    role_attr_flags: SUPERUSER,LOGIN
  become: true
  become_user: postgres

- name: Grant privileges to user
  postgresql_privs:
    db: "{{ nyaapantsu_dbname }}"
    priv: ALL
    roles: "{{ nyaapantsu_user }}"
    state: present
    type: database
  become: true
  become_user: postgres

- name: Add custom pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/9.6/data/pg_hba.conf
  become: true
  become_user: postgres

- name: Add .pgpass
  template:
    src: pgpass.j2
    dest: ~/.pgpass
    mode: 0600

- name: Reload postgres
  systemd:
    name: postgresql-9.6
    state: reloaded
  become: true

- include: pgpool.yml
  when: nyaapantsu_use_pgpool == True
